### ISSUE TITLE
Volume Randomly Goes Lower and Lower (Phantom Button Presses)

### ISSUE THREAD

**Issue by syalam** [JoeBorn/sonr#10]
SHA: e4e5bd10ca05fa8cdc2ba26ef86971d6f626d8a3

Phone: Motorola Droid X
Tester: Sheehan
Music Player: Pandora

After about 30-45 minutes volume started to go down by itself.

This is possibly the "phantom button press" that has been reported many times since we started this project.

**Comment by reshapiro** [comment]
Do we have Android logs for this run?  In general do we have access to logs from test runs?

I've seen almost no spurious signals for some time now, and the few cases when I do see them they follow immediately on a real signal, within one second, probably indicating a framing bug in the audio analyzer code.  I plan to start a run this morning and leave it going all day to see if I can replicate this.

**Comment by syalam** [comment]
Volume issue is most likely hardware related, my hunch as it occurred on a very noisy song.

Just encountered it again:

Samsung Galaxy S
Around 9:55AM MST
Pandora
Ace of Spades (Live) by Motorhead

Logcat dump: https://gist.github.com/64014166299222292ab2

**Comment by syalam** [comment]
Samsung Galaxy S
Pandora
1:33 - 1:35PM Logcat showing UNKNOWN button press command
Song is Reset by Mute Math

Logcat dump: https://gist.github.com/234be8cdd98ba155f1a8

**Comment by syalam** [comment]
Samsung Galaxy S
Pandora
UNKNOWN button press command
Singularity by Gordian Knot

**Comment by syalam** [comment]
Unable to reproduce this on HTC EVO 4G where I was experiencing VOLUME UP.

Joe are you still having this problem?

**Comment by syalam** [comment]
This seems to be resolved, though we are having spurious signals, this specific case has been mitigated with the additional 2/3 check.

**Comment by TrailrunnerJim** [comment]
I have a Galaxy S4 and I am having this same problem. The volume just keeps dropping all of the way down. It happens after 30 mins or so. Have only used Pandora so do not know if that is part of the issue or if it happens with other software.

**Comment by JoeBorn** [comment]
Jim, please try http://share.sonrlabs.com/pub/apk/SONR-1.20.apk  and let us know if it helps.  The official download will be updated to this shortly, so you can also just wait for that.  Let us know how it goes.

**Comment by pdattaSonr** [comment]
Thanks Joe for responding.

On Sunday, June 30, 2013, JoeBorn wrote:

> Jim, please try http://share.sonrlabs.com/pub/apk/SONR-1.20.apk and let
> us know if it helps. The official download will be updated to this shortly,
> so you can also just wait for that. Let us know how it goes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JoeBorn/sonr/issues/10#issuecomment-20257491
> .

## 

_http://www.sonrlabs.com/_
_pdatta@sonrlabs.com_
_718.781.1878 (m)_
_1871@Chicago_
