### ISSUE TITLE
 EVO 3d doesn't respond to remote "dies"

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#14]
autostarts, but then the remote (or dock housing) buttons don't work.  Sometimes doesn't autostart and even gives "dock not detected." Basically this version simply doesn't work with this phone.  I uninstalled and reinstalled just to make sure it wasn't a bad install.

This seems about unchanged through to .71, autostarts, but at some, relatively quick, point, the remote dies. has been happening since testing with evo 3D (.62)

---

Android seems to be killing the ToggleSONR Class. See Joe's log on his PHOTON:

https://gist.github.com/fa1ee036ddc73665fd01

improved substantially in .74, but I still had trouble.  Had to restart once right away, and then after restarting it died after about 30 minutes.

.76 seems same as .74, dies sometimes immediately, sometimes over tens of minutes

**Comment by syalam** [comment]
resolved w/ 0.74 apk

**Comment by syalam** [comment]
I think we can consolidate this with #12 -- but again, re-running burnin test with HTC EVO 3D and 0.77

**Comment by syalam** [comment]
30 Minute burn-in successful, running Pandora. Remote hasn't died.

**Comment by syalam** [comment]
1 hour burn in successful
3 hour burn in successful

Testing overnight burn-in

**Comment by syalam** [comment]
24 hour burn in successful. Closing issue.

**Comment by JoeBorn** [comment]
still not working on Joes EVO 3D on .84

**Comment by syalam** [comment]
For the sake of testing and isolating a problem, would you be able to reformat your EVO 3D and re-install SONR and run through this test?

**Comment by JoeBorn** [comment]
ok, well wait until I'm back from M, and I'll do this.

On Mon, Feb 27, 2012 at 10:19 AM, Sheehan Alam
reply@reply.github.com
wrote:

> For the sake of testing and isolating a problem, would you be able to reformat your EVO 3D and re-install SONR and run through this test?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JoeBorn/sonr/issues/14#issuecomment-4196797

## 

Joe Born
Neuros Technology Intl., LLC
twitter: http://twitter.com/neurostech
jborn@neurostechnology.com
IRC:  #neuros (freenode.net)
Skype: JoeBorn
cell: 773-442-2676 (US)
cell: 86-136-40134556 (China)

**Comment by syalam** [comment]
Keep me updated on 0.86 + fresh reformat

**Comment by pdattaSonr** [comment]
Merged with #39 due to similarity in issues.

**Comment by pdattaSonr** [comment]
Merged with #39 due to similarity in problem category.

**Comment by pdattaSonr** [comment]
Merged with #39 due to similarity in problem category.
