### ISSUE TITLE
some button presses are ignored in .72

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#23]
testing with the moto xprt, I do see some legitimate button presses being ignored (only 2 of 3 bytes match).  This is probably something we can live with, although it would be better to try to dial in the algorithm a bit at a lower level I think.

**Comment by syalam** [comment]
can you reproduce this on 0.77?

**Comment by syalam** [comment]
is this still an issue?

**Comment by JoeBorn** [comment]
I'm testing with .80 now

Joe

On Wed, Feb 1, 2012 at 12:03 AM, Sheehan Alam <
reply@reply.github.com

> wrote:
> 
> is this still an issue?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JoeBorn/sonr/issues/23#issuecomment-3754197

## 

Joe Born
Neuros Technology Intl., LLC
twitter: http://twitter.com/neurostech
jborn@neurostechnology.com
IRC:  #neuros (freenode.net)
Skype: JoeBorn
cell: 773-442-2676 (US)
cell: 86-136-40134556 (China)

**Comment by syalam** [comment]
consolidating this with issue https://github.com/JoeBorn/sonr/issues/33
