### ISSUE TITLE
dock not detected error

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#24]
moto xprt .72 started google music ok, exited when back to home (via home press on remote) and now getting dock not detected error when I try to select players. emailed logcat file to Richard and Sheehan.

**Comment by syalam** [comment]
is this an issue, after you test with the reformatted xprt ?

**Comment by JoeBorn** [comment]
I only saw it once and not since, we can close this bug and I'll re-enter
if I see it again.

Joe

On Thu, Jan 19, 2012 at 3:39 PM, Sheehan Alam <
reply@reply.github.com

> wrote:
> 
> is this an issue, after you test with the reformatted xprt ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JoeBorn/sonr/issues/24#issuecomment-3574813

## 

Joe Born
Neuros Technology Intl., LLC
twitter: http://twitter.com/neurostech
jborn@neurostechnology.com
IRC:  #neuros (freenode.net)
Skype: JoeBorn
cell: 773-442-2676 (US)
cell: 86-136-40134556 (China)

**Comment by syalam** [comment]
i was able to reproduce
1. select media player
2. hit HOME
3. select media player
4. DOCK NOT FOUND

**Comment by JoeBorn** [comment]
I don't know, I can go back to a previous version and try, but with the
current version I can do the below and not get DNF.

Joe

On Thu, Jan 19, 2012 at 4:24 PM, Sheehan Alam <
reply@reply.github.com

> wrote:
> 
> i was able to reproduce
> 1. select media player
> 2. hit HOME
> 3. select media player
> 4. DOCK NOT FOUND
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JoeBorn/sonr/issues/24#issuecomment-3575514

## 

Joe Born
Neuros Technology Intl., LLC
twitter: http://twitter.com/neurostech
jborn@neurostechnology.com
IRC:  #neuros (freenode.net)
Skype: JoeBorn
cell: 773-442-2676 (US)
cell: 86-136-40134556 (China)

**Comment by syalam** [comment]
resolved.
