### ISSUE TITLE
"always use this choice" checkbox causes several major issues

### ISSUE THREAD

**Issue by reshapiro** [JoeBorn/sonr#25]
If the "always use this choice" checkbox is checked, the SONR app will stop showing any media app choices until it (SONR) is reinstalled.

Checking this checkbox also breaks the un-plug/re-plug functionality: once the phone is unplugged it will not be able to reestablish a connection to the dock until the app is restarted.

Observed on Samsung Nexus S

**Comment by reshapiro** [comment]
Is this fixed?  Seems better behaved here though I haven't tried the latest set of updates  in bd5b1dd6c2e2fd3919383618886ca8ed60f58cd2

**Comment by syalam** [comment]
resolved 0.78
