### ISSUE TITLE
Debug Logs Enhancements: Fix Android lint warnings

### ISSUE THREAD

**Issue by reshapiro** [JoeBorn/sonr#26]
We should fix these warnings produced Android lint.  For more details, update the Eclipse plugin and run Lint from there.  Selecting a line in the display will tell you more.

Scanning .: ...................
res/layout/intro.xml:34: Warning: Duplicate id @+id/intro_msg, already defined earlier in this layout [DuplicateIds]
        android:id="@+id/intro_msg"
        ^
res/layout/configuration_listview_row.xml:16: Warning: Avoid using "px" as units; use "dp" instead [PxUsage]
            android:textSize="40px" android:layout_weight="1"/>
            ^
res/layout/configuration_listview_row.xml:13: Warning: Use a layout_width of 0dip instead of fill_parent for better performance [InefficientWeight]
            android:layout_width="fill_parent"
            ^
res/layout/main.xml:29: Warning: Use a layout_height of 0dip instead of wrap_content for better performance [InefficientWeight]
         android:layout_height="wrap_content" android:layout_weight="1"/>  
         ^
res/layout/music_select_main.xml:18: Warning: Use a layout_height of 0dip instead of fill_parent for better performance [InefficientWeight]
        android:layout_height="fill_parent"
        ^
res/layout/music_select_main.xml:50: Warning: Nested weights are bad for performance [NestedWeights]
            android:layout_weight="2"
            ^
res/layout/terms.xml:28: Warning: Nested weights are bad for performance [NestedWeights]
      android:layout_weight=".5"
      ^
res/drawable-mdpi/button_background.xml: Warning: The resource R.drawable.button_background appears to be unused [UnusedResources]
Warning: The resource R.drawable.filter appears to be unused [UnusedResources]
Warning: The resource R.drawable.splash_logo appears to be unused [UnusedResources]
res/layout/configuration_activity.xml: Warning: The resource R.layout.configuration_activity appears to be unused [UnusedResources]
res/layout/main.xml: Warning: The resource R.layout.main appears to be unused [UnusedResources]
res/values/strings.xml: Warning: The resource R.string.crash_toast_text appears to be unused [UnusedResources]
res/values/strings.xml: Warning: The resource R.string.default_player_msg appears to be unused [UnusedResources]
res/values/strings.xml: Warning: The resource R.string.featured_desc appears to be unused [UnusedResources]
res/values/strings.xml: Warning: The resource R.string.featured_title appears to be unused [UnusedResources]
res/values/strings.xml: Warning: The resource R.string.service_name appears to be unused [UnusedResources]
res/layout/textview.xml: Warning: The resource R.layout.textview appears to be unused [UnusedResources]
res/layout/configuration_listview_row.xml:6: Warning: This LinearLayout layout or its LinearLayout parent is possibly useless [UselessParent]
    <LinearLayout
    ^
res/drawable-hdpi/filter.png: Warning: The image filter.png varies significantly in its density-independent (dip) size across the various density versions: drawable-ldpi/filter.png: 43x39 dp (32x29 px), drawable-mdpi/filter.png: 32x29 dp (32x29 px), drawable-hdpi/filter.png: 21x19 dp (32x29 px) [IconDipSize]
res/drawable-mdpi/pandora_radio.png: Warning: The image pandora_radio.png varies significantly in its density-independent (dip) size across the various density versions: drawable-hdpi/pandora_radio.png: 341x341 dp (512x512 px), drawable-mdpi/pandora_radio.png: 72x72 dp (72x72 px) [IconDipSize]
res/drawable-hdpi/sonr_logo.png: Warning: The image sonr_logo.png varies significantly in its density-independent (dip) size across the various density versions: drawable-ldpi/sonr_logo.png: 249x91 dp (187x68 px), drawable-mdpi/sonr_logo.png: 187x68 dp (187x68 px), drawable-hdpi/sonr_logo.png: 125x45 dp (187x68 px) [IconDipSize]
res/drawable-hdpi/sonr_off.png: Warning: The image sonr_off.png varies significantly in its density-independent (dip) size across the various density versions: drawable-ldpi/sonr_off.png: 96x96 dp (72x72 px), drawable-mdpi/sonr_off.png: 72x72 dp (72x72 px), drawable-hdpi/sonr_off.png: 48x48 dp (72x72 px) [IconDipSize]
res/drawable-hdpi/sonr_on.png: Warning: The image sonr_on.png varies significantly in its density-independent (dip) size across the various density versions: drawable-ldpi/sonr_on.png: 96x96 dp (72x72 px), drawable-mdpi/sonr_on.png: 72x72 dp (72x72 px), drawable-hdpi/sonr_on.png: 48x48 dp (72x72 px) [IconDipSize]
res/drawable-hdpi/splash_logo.png: Warning: The image splash_logo.png varies significantly in its density-independent (dip) size across the various density versions: drawable-ldpi/splash_logo.png: 420x147 dp (315x110 px), drawable-mdpi/splash_logo.png: 315x110 dp (315x110 px), drawable-hdpi/splash_logo.png: 210x73 dp (315x110 px) [IconDipSize]
res/drawable-mdpi/winamp.png: Warning: The image winamp.png varies significantly in its density-independent (dip) size across the various density versions: drawable-hdpi/winamp.png: 200x200 dp (300x300 px), drawable-mdpi/winamp.png: 70x70 dp (70x70 px) [IconDipSize]
res/drawable-mdpi/filter.png: Warning: The filter.png icon has identical contents in the following configuration folders: drawable-hdpi, drawable-ldpi, drawable-mdpi [IconDuplicatesConfig]
res/drawable-mdpi/sonr_logo.png: Warning: The sonr_logo.png icon has identical contents in the following configuration folders: drawable-hdpi, drawable-ldpi, drawable-mdpi [IconDuplicatesConfig]
res/drawable-mdpi/sonr_off.png: Warning: The sonr_off.png icon has identical contents in the following configuration folders: drawable-hdpi, drawable-ldpi, drawable-mdpi [IconDuplicatesConfig]
res/drawable-mdpi/splash_logo.png: Warning: The splash_logo.png icon has identical contents in the following configuration folders: drawable-hdpi, drawable-ldpi, drawable-mdpi [IconDuplicatesConfig]
res/drawable-mdpi: Warning: Missing the following drawables in drawable-mdpi: dianddock.png (found in drawable-hdpi) [IconDensities]
res/drawable-mdpi/sonr_on.png: Warning: The following unrelated icon files have identical contents: sonr_icon.png, sonr_on.png, sonr_on.png, sonr_on.png [IconDuplicates]
Warning: Missing density variation folders in res: drawable-xhdpi [IconMissingDensityFolder]
res/layout/intro.xml:8: Warning: [Accessibility] Missing contentDescription attribute on image [ContentDescription]
    <ImageView
    ^
res/layout/intro.xml:16: Warning: [Accessibility] Missing contentDescription attribute on image [ContentDescription]
    <ImageView
    ^
res/layout/intro.xml:44: Warning: [Accessibility] Missing contentDescription attribute on image [ContentDescription]
        <ImageButton
        ^
res/layout/intro.xml:53: Warning: [Accessibility] Missing contentDescription attribute on image [ContentDescription]
        <ImageButton
        ^
res/layout/manage_applications_item.xml:14: Warning: [Accessibility] Missing contentDescription attribute on image [ContentDescription]
    <ImageView android:id="@+id/app_icon"
    ^
res/layout/toggle_apwidget.xml:8: Warning: [Accessibility] Missing contentDescription attribute on image [ContentDescription]
<ImageView android:id="@+id/Icon" 
^
res/layout/configuration_listview_row.xml:15: Warning: [I18N] Hardcoded string "MainText", should use @string resource [HardcodedText]
            android:text="MainText"
            ^
res/layout/intro.xml:38: Warning: [I18N] Hardcoded string "Recommended players:", should use @string resource [HardcodedText]
        android:text="Recommended players:" />
        ^
res/layout/intro.xml:70: Warning: [I18N] Hardcoded string "OK", should use @string resource [HardcodedText]
        android:text="OK" />
        ^
res/layout/main.xml:14: Warning: [I18N] Hardcoded string "Default player", should use @string resource [HardcodedText]
   android:text="Default player"
   ^
res/layout/music_select_main.xml:51: Warning: [I18N] Hardcoded string "always use this choice", should use @string resource [HardcodedText]
            android:text="always use this choice" />
            ^
res/layout/music_select_main.xml:57: Warning: [I18N] Hardcoded string "None", should use @string resource [HardcodedText]
            android:text="None" />
            ^
res/layout/music_select_main.xml:65: Warning: [I18N] Hardcoded string "OK", should use @string resource [HardcodedText]
            android:text="OK" />
            ^
res/layout/terms.xml:25: Warning: [I18N] Hardcoded string "Disagree", should use @string resource [HardcodedText]
     android:text="Disagree" 
     ^
res/layout/terms.xml:32: Warning: [I18N] Hardcoded string "Agree", should use @string resource [HardcodedText]
   android:text="Agree"
   ^

0 errors, 48 warnings

**Comment by syalam** [comment]
while its good practice to move everything to a strings resource file (for localization purposes) etc this is low priority. thanks for Lint'ing this. It is still good to pursue this after we resolve the bigger ticket items.

**Comment by reshapiro** [comment]
I agree, this is very low priority.  Might be nice to fix these things befeore we go open-source.
