### ISSUE TITLE
Essential gui fix: let the user know when dock detection is in progress

### ISSUE THREAD

**Issue by reshapiro** [JoeBorn/sonr#27]
Since we now wait up to 5 seconds to establish a logical connection to the dock, we need the gui to indicate this fact.  Otherwise users will certainly think something's wrong and will keep hitting the buttons.  Very important to usability to get this right.

To see the problem, just start the app with the dock turned off or not physically connected to the phone.

**Comment by syalam** [comment]
implemented.

**Comment by reshapiro** [comment]
Might be worth incrementing the version# since it's a user-visible change.
