### ISSUE TITLE
"dock not detected" persists even when dock reconnected

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#28]
.76 testing with evo 3D.  

start app, try to connect to media player without dock connected (physically disconnected) and get "dock not detected" (as of course appropriate) then connect dock and continue to get this message, which even restarting the app does not cure.  Only restarting the machine seems to fix.

**Comment by reshapiro** [comment]
I don't see that behavior here with the Samsung.  As soon as a physical connection is in place the dock is found.

**Comment by JoeBorn** [comment]
I note this varies between the v5 and v6 (production) docks I have here.  I need to try to replicate and report exactly what I'm seeing.

**Comment by reshapiro** [comment]
I've using the new dock, which I guess is v6.  But I just tried the older one and that seems ok too.

**Comment by syalam** [comment]
unable to reproduce this on a production dock, running 0.77 on an HTC EVO 3D

**Comment by JoeBorn** [comment]
seems to work ok on Photon, although I went back to home and it seemed to
detect the dock even when unplugged.  I guess this is a bug, although
connecting and disconnecting never seemed to cause problems with the dock.

On Sun, Jan 29, 2012 at 8:08 PM, Sheehan Alam <
reply@reply.github.com

> wrote:
> 
> unable to reproduce this on a production dock, running 0.77
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JoeBorn/sonr/issues/28#issuecomment-3713474

## 

Joe Born
Neuros Technology Intl., LLC
twitter: http://twitter.com/neurostech
jborn@neurostechnology.com
IRC:  #neuros (freenode.net)
Skype: JoeBorn
cell: 773-442-2676 (US)
cell: 86-136-40134556 (China)

**Comment by syalam** [comment]
unable to detect dock, while unplugged on test batch. I don't have a Photon unfortunately.

**Comment by syalam** [comment]
i was able to reproduce this on an HTC EVO 3D.
1. Select media player
2. Click HOME
3. Unplug DOCK
4. Select Media Player
5. DOCK DETECTED

**Comment by JoeBorn** [comment]
Seems to be the case on first install (still exists on .80):

Behavior same for xprt and evo 3D
1. deleted the old app
2. installed (this time from email attachment, but I've seen this from installing from eclipse too, not sure about the market)
3. Start up sonr, get dock not found
4. force kill sonr, then restart
5. dock now found

On the evo 3d

I then get 
6. remote does not work
7.restart sonr (from icon not force kill)
8. remote works (but dies after a few minutes, this is a known, entered bug)

**Comment by JoeBorn** [comment]
Seems to be the case on first install (still exists on .80):

Behavior same for xprt and evo 3D
1. deleted the old app
2. installed (this time from email attachment, but I've seen this from installing from eclipse too, not sure about the market)
3. Start up sonr, get dock not found
4. force kill sonr, then restart
5. dock now found

On the evo 3d

I then get 
6. remote does not work
7.restart sonr (from icon not force kill)
8. remote works (but dies after a few minutes, this is a known, entered bug)

**Comment by syalam** [comment]
consolidated w/ 29
