### ISSUE TITLE
app requires restart to perform properly

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#29]
Probably #28 should be closed and replaced with this one.

As noted there, the XPRT and EVO 3D don't perform well when the app first runs after install.  Then after killing and restarting, it's ok.

On the Atrix, the remote was horribly unresponsive (although I didn't get dock not detected) it probably detected 10% of button presses, after killing and restarting, seems to be performing fine.

**Comment by syalam** [comment]
Unable to reproduce on both Atrix and EVO 3D. Both are running Cyanogenmod however.

Reproduction Steps:
1. Uninstall SONR
2. Install SONR
3. Everything is good

Reproduction Step 2:
1. Install SONR from Eclipse (without uninstalling)
2. Everything is good

Reproduction Step 3
1. Install SONR from Android Market (without uninstalling)
2. Everything is good
