### ISSUE TITLE
IllegalStateException when dismissing the 'Searching for SONR Dock...' progresss dialog

### ISSUE THREAD

**Issue by reshapiro** [JoeBorn/sonr#30]
In one run I started the app with the phone disconnected.   The dock was of course not found, as expected. But the 'dismiss' call on the progress dialog threw an IllegalStateException, which hung the app.

I can't replicate this issue, noting it here for reference.

SONR v81
Samsung Nexus S

**Comment by syalam** [comment]
this should be resolved from 0.84
