### ISSUE TITLE
more advanced debugging needed

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#35]
we need to build on the current email feedback system in the following ways
1. include a menu that allows the user to pull down from a list of issues (or write in "other" issues) as well as the app they are experiencing trouble with.
2. submit to us state information about the system (hardware version, android version, apps installed, etc)

This information should be compilable in a google doc or the like that will allow us to see the state of issue with various system configurations to determine if a particular version of android or an app is causing new issues.

**Comment by syalam** [comment]
Agreed. I'll add this to the list

**Comment by syalam** [comment]
feedback form added that collects diagnostics, along with common issues a user can select if he encounters them
