### ISSUE TITLE
Incompatibility with Top 3rd-Party Apps (#issues = 4)

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#36]
a) : Youtube Client Controls Don't Work 
is the youtube client open source?  if so can we modify to respond to intents?  are there others that either already work or can be modified?

b) Audible
Audible Does Not Respond to Play/Pause - doesn't work on either photon Q or EVO 3D

c) Samsung Fascinate - Samsung Fascinate only volume buttons work 
as reported in Gadgeteer review: http://the-gadgeteer.com/2012/02/18/digital-innovations-universal-speaker-dock-for-android-review/

Syalam>> He is probably running a music player we don't support (com.android.music). I really want to filter this out from our media player list so reviewers/users don't encounter it, but unfortunately, it could also be the primary player for most people.

com.android.music also known as (Music [not to be confused with Google music], or HTC Music on certain devices) is the default Android music player, and as noted before via e-mails, I checked out the source code for this app on android.org (open source android code) and there is a bit of code that rejects remote broadcasts. It handles Volume controls because Android treats those as system level commands and not intent level broadcasts that 3rd parties consume.

I have a Samsung Fascinate that works with Winamp/Pandora/Amazon MP3/Spotify.

JB>> ok, please verify that this is the case with the reviewer. If you have trouble let me know.

Syalam>> James responded with the following:

"Let me try Pandora and Winamp, I will add them to the review as well if I can. I will let you know how they work, I should be using those anyway becasue I am not a big fan of stock players"

He was presumably using the stock player (com.android.music).

d) photon Q sonr continues to "spin" even after connecting
startup the app, select google music player, the sonr spinner continues to run, although the system tray icon appears stating "sonr connected." the user has to back out and then re select the media player. Then it works normally.

**Comment by syalam** [comment]
unfortunately the youtube app is not part of android.org

**Comment by JoeBorn** [comment]
Are there any open source YouTube browsers?
On Mar 8, 2012 9:50 PM, "Sheehan Alam" <
reply@reply.github.com>
wrote:
