### ISSUE TITLE
dock does not detect properly with HTC One X

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#40]
John Garcia <> wrote:
... So right now I was using my dock and I figured I would give the Sonr App another try.  Well, this time it worked and worked very well.  The strange this is this. I left the room and my son unplugged my phone to use it.  He then put the phone back on the dock without the adapter you sent me and the app found the dock.  The phone does not show that a jack is plugged in (no headphone icon) but the app and audio still worked.  I then turned off the dock, unplugged my phone and put the jack back in and the Sonr app didnt recognize the dock again.  I connected the adapter again and again the dock Sonr App did not recognize the dock, but when I removed the adapter and plugged the original cable in to the phone, it worked again. I tried this several times and it seems the Sonr app will only recognize the dock once I have plugged in the adapter you sent me and then remove it.  Does this make sense? I know it does not to me, but it works and thats what matters. I dont mind taking that extra step because it only take 20 seconds.  So thats where I stand now with the dock. I hope this information helps.

+++++++++++++++++++
JB note:  cable he refers to is a cross over audio cable per slee specifications.

**Comment by pdattaSonr** [comment]
Merged with #39 due to similar nature of issue.
