### ISSUE TITLE
sound through speakers even when headset plugged in

### ISSUE THREAD

**Issue by JoeBorn** [JoeBorn/sonr#46]
playing audible on Photon Q, the sound continues to come out of the phone speaker even when a headset is plugged into the phone (using sonr v.95)

**Comment by JoeBorn** [comment]
Not clear this is actually a Sonr issue.  May just be a photon Q issue as its still there even with Sonr uninstalled and there appear to be complaints of this from other Photon Q users (without this app).  Also it happened right after an update.

**Comment by pdattaSonr** [comment]
merged with #37 due to similar problem bucket.
